name: ardubot
hostname: localhost
port: 8080
gadgets:
- ardubot
- phone
- opz
cables:
- cable: cc2ard
  tx_gadget: opz
  rx_gadget: ardubot
- cable: motion2motor
  tx_gadget: phone
  rx_gadget: ardubot
