name: ardubot
hostname: localhost
port: 8080
gadgets:
- ardubot
- phone
- opz
cables:
- msg_func: cc2ard
  tx_gadget: opz
  rx_gadget: ardubot
- msg_func: motion2motor
  tx_gadget: phone
  rx_gadget: ardubot
