name: blsm
hostname: localhost
port: 8080
gadgets:
- blossom
- phone
- opz
cables:
- cable: note2motor
  tx_gadget: opz
  rx_gadget: blossom
  input_event: midi_on
  output_event: position
- cable: cc2motor
  tx_gadget: opz
  rx_gadget: blossom
  input_event: midi_cc
  output_event: position
- cable: motion2motor
  tx_gadget: phone
  rx_gadget: blossom
  input_event: device_motion
  output_event: position