gadgets:
- blsm_dxl
- blsm_phone
- microphone
- pygame_keys
- chatbot
cables:
- cable: key2mic
  tx_gadget: pygame_keys
  rx_gadget: microphone
- cable: text2yes_no_prompt
  tx_gadget: microphone
  rx_gadget: chatbot
- cable: motion2motor
  tx_gadget: blsm_phone
  rx_gadget: blsm_dxl
- cable: response2blsm
  tx_gadget: chatbot