gadgets:
- dxl_motor
- phone
- opz
cables:
- cable: note2motor
  tx_gadget: opz
  rx_gadget: dxl_motor
- cable: cc2motor
  tx_gadget: opz
  rx_gadget: dxl_motor
- cable: motion2motor
  tx_gadget: phone
  rx_gadget: dxl_motor