gadgets:
- dxl_motor
- phone
- opz
cables:
- msg_func: note2motor
  tx_gadget: opz
  rx_gadget: dxl_motor
- msg_func: cc2motor
  tx_gadget: opz
  rx_gadget: dxl_motor
- msg_func: motion2motor
  tx_gadget: phone
  rx_gadget: dxl_motor