name: mpi
hostname: localhost
port: 8080
gadgets:
  # TODO - pibutton first will call pause
- pibutton
- picamera
messages:
- msg_func: button2cam
  tx_gadget: pibutton
  rx_gadget: picamera
- msg_func: dpad2shutter
  tx_gadget: pibutton
  rx_gadget: picamera
