name: ardubot
type: ArduinoRobot
# usb_port: /dev/cu.usbmodem1101
usb_port: /dev/cu.usbserial-ADAQDbKpQ
# usb_port: /dev/cu.usbmodem212101
baud_rate: 115200
# baud_rate: 57600
# baud_rate: 9600
timeout: 2
motors: # use these same names as kwargs to constructors
- name: tower_1
  id: 10
  position:
    reset: 0
    min: -40
    max: 140
