name: ardubot
type: ArduinoBot
hostname: localhost
port: 9000
usb_port: /dev/cu.usbmodem1101
baud_rate: 115200
timeout: 2
motors: # use these same names as kwargs to constructors
- name: tower_1
  id: 2
  position:
    reset: 0
    min: -40
    max: 140
