name: mpibuttons
type: PiButton
hostname: localhost
port: 9000
usb_port: /dev/tty.usbserial-FT1SF1UM
# usb_port: /dev/tty.usbserial-FT2KQD1N
baud_rate: 57600
buttons:
  manual_button: 20
  button: 5
leds:
  led: 15
  