type: ArduinoRobot
usb_port: /dev/cu.usbserial-ADAQDbKpQ
baud_rate: 57600
timeout: 2
motors:
- name: base
  id: 9
  position:
    reset: 0
    min: -40
    max: 140
- name: tower_1
  id: 10
  position:
    reset: 0
    min: -40
    max: 140
- name: tower_2
  id: 6
  position:
    reset: 0
    min: -40
    max: 140
- name: tower_3
  id: 5
  position:
    reset: 0
    min: -40
    max: 140
