type: DynamixelRobot
usb_port: /dev/tty.usbmodem212401
baud_rate: 1000000
motors: # use these same names as kwargs to constructors
- name: tower_1
  model: xl320
  id: 1
  mode: position
  position:
    reset: 0
    min: -40
    max: 140
  moving_speed: 400
- name: tower_2
  model: xl320
  id: 2
  mode: position
  position:
    reset: 0
    min: -40
    max: 140
  moving_speed: 400
- name: tower_3
  model: xl320
  id: 3
  mode: position
  position:
    reset: 0
    min: -40
    max: 140
  moving_speed: 400
- name: base
  model: xl320
  id: 4
  mode: position
  position:
    reset: 0
    min: -40
    max: 140
  moving_speed: 400