name: phone
type: Phone
hostname: localhost
port: 8080
route_urls:
  /: index.html
  /broadcast: broadcast.html
event_kwargs:
  # record:
  #   namespace: /phone
  device_motion:
    # namespace: /
    namespace: /phone
  