name: testphone
type: Phone
route_urls:
  /: index.html
  /broadcast: broadcast.html
event_kwargs:
  # record:
  #   namespace: /phone
  device_motion:
    namespace: /phone
messages:
- msg_func: note2motor
  tx_gadget: opz
  rx_gadget: blossom
  